# Project identity
sonar.projectKey=FIAP-15SOAT_oficina-mecanica-lambda-customer-auth
sonar.organization=fiap-15soat
sonar.projectName=oficina-mecanica-lambda-customer-auth
# sonar.projectVersion=1.0

# Analysis scope
sonar.sources=src,scripts
sonar.tests=test
sonar.exclusions=node_modules/**,dist/**,coverage/**,scripts/**,src/bootstrap.ts,src/**/*.interface.ts,src/**/*.dto.ts,src/**/*.request.ts,src/**/*.response.ts,src/**/*.catalog.ts
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# TypeScript
sonar.typescript.tsconfigPaths=tsconfig.json

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality gate — wait for the gate result and fail the job if it is not passed.
sonar.qualitygate.wait=true
